FROM registry.astralinux.ru/library/astra/ubi18:latest
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git ca-certificates pkg-config \
    redis-tools \
 && rm -rf /var/lib/apt/lists/*

# hiredis (через CMake -> появится hiredisConfig.cmake)
RUN git clone --depth 1 https://github.com/redis/hiredis.git /tmp/hiredis \
 && cmake -S /tmp/hiredis -B /tmp/hiredis/build -DCMAKE_BUILD_TYPE=Release \
 && cmake --build /tmp/hiredis/build -j"$(nproc)" \
 && cmake --install /tmp/hiredis/build \
 && rm -rf /tmp/hiredis

# redis-plus-plus (redis++)
RUN git clone --depth 1 https://github.com/sewenew/redis-plus-plus.git /tmp/redis-plus-plus \
 && cmake -S /tmp/redis-plus-plus -B /tmp/redis-plus-plus/build \
      -DCMAKE_BUILD_TYPE=Release \
      -DREDIS_PLUS_PLUS_BUILD_TEST=OFF \
      -DREDIS_PLUS_PLUS_BUILD_SHARED=ON \
 && cmake --build /tmp/redis-plus-plus/build -j"$(nproc)" \
 && cmake --install /tmp/redis-plus-plus/build \
 && rm -rf /tmp/redis-plus-plus

ENV CMAKE_PREFIX_PATH=/usr/local

WORKDIR /tmp/appsrc
COPY CMakeLists.txt ./
COPY src/loader.cpp src/worker.cpp src/
RUN cmake -S . -B /tmp/build-rts -DCMAKE_BUILD_TYPE=Release \
 && cmake --build /tmp/build-rts --target loader worker -j"$(nproc)" \
 && install -m 0755 /tmp/build-rts/loader /usr/local/bin/loader \
 && install -m 0755 /tmp/build-rts/worker /usr/local/bin/worker

WORKDIR /app